Tests: robustify the sandbox
Running the nepomuk tests always timed out for me. I found that this was
because the nepomukserver was failing to start. There are two problems
here:

1) if the sandbox fails to start, it should just fail, not
timeout.

2) nepomukserver should not fail to start.

This patch fixes 1) by adding return value checking to the sandbox
script; if kdeinit4 & friends fail to start the test fails instantly

2) turned out to be because the nepomukserver could not
connect to the (local) X server. To fix this, I changed the script to be
started through xvfb-run, which starts a virtual X server for it to
connect to.

Finally, start the nepomukserver we just built, rather than the
installed one.

REVIEW: 112134

diff --git a/autotests/lib/tools/nepomuk-sandbox-begin.sh.in b/autotests/lib/tools/nepomuk-sandbox-begin.sh.in
--- a/autotests/lib/tools/nepomuk-sandbox-begin.sh.in
+++ b/autotests/lib/tools/nepomuk-sandbox-begin.sh.in
@@ -29,14 +29,35 @@ mkdir -p $KDEHOME/share/config
 cp @NEPOMUK_TESTLIB_DATA_DIR@/nepomukserverrc $KDEHOME/share/config/
 
 # start kde basics
+SANDBOX_FAILED=false
 echo "Starting new KDE session in $KDEHOME..."
 kbuildsycoca4 2> /dev/null
+if [ $? != 0 ]; then
+    echo "failed to run kbuildsycoca4"
+    SANDBOX_FAILED=true
+fi
+
 kdeinit4 2> /dev/null
+if [ $? != 0 ]; then
+    echo "failed to start kdeinit4"
+    SANDBOX_FAILED=true
+fi
+
 qdbus org.kde.kded /kded org.kde.kded.loadSecondPhase 2> /dev/null
 echo "Started..."
 
 # Start the nepomuk server (which will automatically start other nepomuk services
 echo "Starting nepomukserver"
-nepomukserver 2> $KDETMP/nepomuk-server.log &
+@CMAKE_BINARY_DIR@/server/nepomukserver 2> $KDETMP/nepomuk-server.log &
 
-export NEPOMUK_TESTLIB_RUNNING=true
+ret=$(ps | grep nepomukserver | wc -l)
+if [ $ret != 1 ]; then
+    echo "failed to start nepomukserver"
+    SANDBOX_FAILED=true
+fi
+
+if ( $SANDBOX_FAILED ); then
+    export NEPOMUK_TESTLIB_RUNNING=false
+else
+    export NEPOMUK_TESTLIB_RUNNING=true
+fi
